# Data Preprocessing


## Importing the libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [18]:
dataset = pd.read_csv('50_Startups.csv') 
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [19]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

### Splitting the dataset into Independent and Dependent Variable

In [31]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values


## Taking care of missing data

In [21]:

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])


## Encoding categorical data into the Dummy Variable
## Encoding X categorical data + HotEncoding

In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
from sklearn.preprocessing import  OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X=np.array(ct.fit_transform(X), dtype = np.float)


## Avoiding the Dummy Variable Trap[most of time libraries done this thing] 



In [23]:
X = X[:, 1:]

## Encoding the Dependent Variable



In [24]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

## Splitting the dataset into the Training set and Test set


In [27]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


## Feature Scaling


In [30]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
y_train=y_train.reshape(-1, 1)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

In [38]:
print(X_train[:5])
print(type(X_train))

[[ 1.73205081 -0.73379939 -0.35006454 -0.78547109  0.1011968 ]
 [-0.57735027  1.36277029 -0.55530319 -1.48117426  0.02734979]
 [ 1.73205081 -0.73379939  0.07935762  0.80133381 -0.55152132]
 [-0.57735027 -0.73379939 -0.54638238  1.32505817  0.07011684]
 [ 1.73205081 -0.73379939  0.43485371 -0.35598663  0.75148516]]
<class 'numpy.ndarray'>


In [39]:
print(X_test[:5])
print(type(X_test))

[[ 1.73205081 -0.73379939 -0.1214952   2.2889053  -0.68032287]
 [-0.57735027 -0.73379939  0.6280306  -1.22069499  0.38557774]
 [ 1.73205081 -0.73379939  0.65490061 -0.49434195  0.21885524]
 [ 1.73205081 -0.73379939 -0.94762148 -1.49417936 -0.30512104]
 [ 1.73205081 -0.73379939  1.77048111 -0.85932667  1.6668808 ]]
<class 'numpy.ndarray'>


In [40]:
print(y_train[:5])
print(type(y_train))

[[ 0.05783149]
 [ 1.21446136]
 [ 0.05783149]
 [-1.09879837]
 [ 0.05783149]]
<class 'numpy.ndarray'>


In [41]:
print(y_test[:5])
print(type(y_test))

[1 0 1 1 1]
<class 'numpy.ndarray'>
