# Artificial Neural Network


# Part 1 - Data Preprocessing


## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset


In [36]:
dataset = pd.read_csv('Churn_Modelling.csv')
print(dataset.head(10))
print(dataset.describe())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0       

## Splitting the dataset into Independent and Dependent Variable

In [56]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

print("-----X----")
print(X[:10])
print(type(X))
print(X.shape)
print("-----y----")
print(y[:10])
print(y.shape)



-----X----
[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]]
<class 'numpy.ndarray'>
(10000, 10)
-----y----
[1 0 1 0 0 1 0 1 0 0]
(10000,)


## Encoding categorical  data(Geography & Gender into number type data )


In [57]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


## make dummy variables for Geography only


In [58]:
print(X[0])
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
[1.0 0.0 0.0 619 'Female' 42 2 0.0 1 1 1 101348.88]


## Encoding categorical  data(Gender into number type data )

In [59]:
print(X[0])
labelencoder_x_2=LabelEncoder()
X[:,4]=labelencoder_x_2.fit_transform(X[:,4])
print(X[0])

[1.0 0.0 0.0 619 'Female' 42 2 0.0 1 1 1 101348.88]
[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


## Remove dummy variables trap


In [60]:
X = X[:, 1:]
print(X[0])

[0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


## Splitting the dataset into the Training set and Test set

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print("-----X_train-------")
print(X_train[:5])
print(type(X_train))
print(X_train.shape)

print("---------X_test------")
print(X_test[:5])
print(type(X_test))
print(X_test.shape)

print("---------y_train------")
print(y_train[:5])
print(type(y_train))
print(y_train.shape)

print("---------y_test------")
print(y_test[:5])
print(type(y_test))
print(y_test.shape)


-----X_train-------
[[0.0 1.0 667 0 34 5 0.0 2 1 0 163830.64]
 [1.0 0.0 427 1 42 1 75681.52 1 1 1 57098.0]
 [0.0 0.0 535 0 29 2 112367.34 1 1 0 185630.76]
 [0.0 1.0 654 1 40 5 105683.63 1 1 0 173617.09]
 [0.0 1.0 850 0 57 8 126776.3 2 1 1 132298.49]]
<class 'numpy.ndarray'>
(8000, 11)
---------X_test------
[[1.0 0.0 597 0 35 8 131101.04 1 1 1 192852.67]
 [0.0 0.0 523 0 40 2 102967.41 1 1 0 128702.1]
 [0.0 1.0 706 0 42 8 95386.82 1 1 1 75732.25]
 [0.0 0.0 788 1 32 4 112079.58 1 0 0 89368.59]
 [1.0 0.0 706 1 38 5 163034.82 2 1 1 135662.17]]
<class 'numpy.ndarray'>
(2000, 11)
---------y_train------
[0 0 0 0 0]
<class 'numpy.ndarray'>
(8000,)
---------y_test------
[0 1 0 0 0]
<class 'numpy.ndarray'>
(2000,)


## Feature Scaling


In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print("-----X_train-------")
print(X_train[:5])
print("---------X_test------")
print(X_test[:5])

-----X_train-------
[[-0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796  0.00666099
  -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945  0.91601335  0.30102557 -1.37744033
  -0.00631193 -0.92159124  0.64259497  0.9687384  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 -1.09168714 -0.94312892 -1.031415
   0.57993469 -0.92159124  0.64259497 -1.03227043  1.48533467]
 [-0.5698444   1.74309049  0.03556578  0.91601335  0.10961719  0.00666099
   0.47312769 -0.92159124  0.64259497 -1.03227043  1.27652776]
 [-0.5698444   1.74309049  2.05611444 -1.09168714  1.73658844  1.04473698
   0.8101927   0.8095029   0.64259497  0.9687384   0.55837842]]
---------X_test------
[[ 1.75486502 -0.57369368 -0.55204276 -1.09168714 -0.36890377  1.04473698
   0.8793029  -0.92159124  0.64259497  0.9687384   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 -1.09168714  0.10961719 -1.031415
   0.42972196 -0.92159124  0.64259497 -1.03227043  0.49587037]
 [

# Part 2 - Now let's make the ANN!

## Importing the Keras libraries and packages

## For Using TensorFlow backend.

In [65]:
import keras

Using TensorFlow backend.


## The sequential module that is required to initialize our neural network 

In [66]:
from keras.models import Sequential

## the dense module that is required to build the layers of our in
## Randomly initialise the weight to small numbers close to zero( but not zero '0')

In [67]:
from keras.layers import Dense

# Initialising the ANN

In [68]:
classifier = Sequential()

## Adding the input layer and the first hidden layer
## add() : Method to add layer in ANN
## Dense() : Randomly initialise the weight to small numbers close to zero( but not zero '0')
## output_dim [ (no of i/p var + no of o/p var)/2][(11+1)/2=6] output_dim = 6
## kernel_initializer = 'uniform' : Randomly initialise the weight  
## activation = 'relu'-> rectifier for hidden layer  activation function 
## No of independent var :1input_dim = 11

classifier.add(Dense(output_dim = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))



## Adding the second hidden layer [the second hidden layer Well it knows what to expect because the first hidden layer was created.]


In [69]:
classifier.add(Dense(output_dim = 6, kernel_initializer = 'uniform', activation = 'relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=6)`
  """Entry point for launching an IPython kernel.


## Adding the output layer
## output_dim = 1 beacause we have only one output.
## activation = 'sigmoid'-> sigmoid for hidden layer  activation function [sigmoid heart of probability aproch]


In [70]:
classifier.add(Dense(output_dim = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
  """Entry point for launching an IPython kernel.


##  dependent variable that has more than two categories like say for example three categories: output parameter ana activation = 'Soft_max'

##  Compiling the ANN [applying stochastic on the whole artificial neural network.]
## compile()  method 
"""optimizer = Adam' is the algorithm you want to use to find the optimal set of weights in the neural networks 
because you know we defined our neural networks it is built with the different layers but the weights are still only initialized.
several types of stochastic and descent algorithm and a very efficient one is called 'Adam'
loss = 'binary_crossentropy' : Stochastic is based on a lost function that you need to optimize to find the optimal weights. 
metrics = ['accuracy'] : metrics accuracy criterion algorithm for weight adjust to improve the models performance"""



In [71]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

##  Fitting the ANN to the Training set
##  use the fit method that will fit our ANN into the training sets.
##  nb_epoch = 100 : epoch is number of times whole training set passed through the ANN
##  epoch is number of times whole training set passed through the ANN 
##  [Algo Of Training the ANN with Stochastic Descent: applying steps 1 to 6 over many epochs.]
##  batch_size = 10 : 
##  Update weight after each observations [ Reinforcement Learning] 
##  or Update weight after batch of observations [Batch Learning].

In [73]:

classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 3s 390us/step - loss: 0.4999 - accuracy: 0.7949
Epoch 2/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4278 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4235 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4207 - accuracy: 0.7961
Epoch 5/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4181 - accuracy: 0.8209
Epoch 6/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4159 - accuracy: 0.8284
Epoch 7/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4141 - accuracy: 0.8288
Epoch 8/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4127 - accuracy: 0.8296
Epoch 9/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4112 - accuracy: 0.8330
Epoch 10/100
8000/8000 [==============================]

Epoch 78/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3999 - accuracy: 0.8350
Epoch 79/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4001 - accuracy: 0.8364
Epoch 80/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4000 - accuracy: 0.8371
Epoch 81/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4001 - accuracy: 0.8364
Epoch 82/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4001 - accuracy: 0.8350
Epoch 83/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4002 - accuracy: 0.8357
Epoch 84/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4000 - accuracy: 0.8361
Epoch 85/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3998 - accuracy: 0.8365
Epoch 86/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3999 - accuracy: 0.8356
Epoch 87/100
8000/8000 [======================

# Part 3 - Making the predictions and evaluating the model

##  Predicting the Test set results

In [77]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


##  Making the Confusion Matrix


In [76]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1557   38]
 [ 282  123]]
